#### Pandas-DataFrame And Series
Pandas is a powerful data manipulation library in Python, widely used for data analysis and data cleaning. It provides two primary data structures: Series and DataFrame. A Series is a one-dimensional array-like object, while a DataFrame is a two-dimensional, size-mutable, and potentially heterogeneous tabular data structure with labeled axes (rows and columns).

In [5]:
import pandas as pd

In [ ]:
## Series
##A Pandas Series is a one-dimensional array-like object that can hold any data type with indexes. It is similar to a column in a table.

import pandas as pd
data=[1,2,3,4,5]
series=pd.Series(data) # pd.Series() converts list or array into a Pandas Series (1D labelled data structure with index and values)
print("Series \n",series)
print(type(series)) # Pandas Series objec

Series
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>

In [12]:
## Create a Series from dictionary
data={'a':1,'b':2,'c':3}
series_dict=pd.Series(data)
print(series_dict)

# When creating a Series from dictionary: keys become index and values become data

a    1
b    2
c    3
dtype: int64

In [ ]:
data=[10,20,30]
index=['a','b','c']
pd.Series(data,index=index)
# In pd.Series(), data and index length must be equal.
# Otherwise Pandas raises ValueError.
# Exception: when using dictionary, missing index values become NaN.

a    10
b    20
c    30
dtype: int64

# # DataFrame is a 2D labelled data structure in pandas with rows and columns, similar to a table or Excel sheet.

In [13]:
## Dataframe
## create a Dataframe from a dictionary of list

data={
    'Name':['Krish','John','Jack'],
    'Age':[25,30,45],
    'City':['Bangalore','New York','Florida'],
    'Domain':['DataAnalyst' ,'DataScientist' , 'ML Engineer']
}
df=pd.DataFrame(data)
print(df)
print(type(df))
# In pandas DataFrame, when using a dictionary of lists, all columns must have the same number of values.
# Otherwise pandas raises: ValueError: All arrays must be of the same length

    Name  Age       City         Domain
0  Krish   25  Bangalore    DataAnalyst
1   John   30   New York  DataScientist
2   Jack   45    Florida    ML Engineer
<class 'pandas.core.frame.DataFrame'>

In [12]:
## Create a Data frame From a List of Dictionaries

data=[
    {'Name':'Krish','Age':32,'City':'Bangalore'},
    {'Name':'John','Age':34,'City':'Bangalore'},
    {'Name':'Bappy','Age':32,'City':'Bangalore' , 'Domain':'DataAnalytics'},
    {'Name':'JAck','Age':32}
    
]
df=pd.DataFrame(data)
print(df)
print(type(df))
## pd.DataFrame(list_of_dict) creates a DataFrame where each dictionary represents one row and dictionary keys become column names.
# Missing keys are filled with NaN

    Name  Age       City         Domain
0  Krish   32  Bangalore            NaN
1   John   34  Bangalore            NaN
2  Bappy   32  Bangalore  DataAnalytics
3   JAck   32        NaN            NaN
<class 'pandas.core.frame.DataFrame'>

In [11]:
df=pd.read_csv('sales_data.csv') # Load the CSV file into a pandas DataFrame
df.head(5) # Display the first 5 rows of the dataset

         Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North

In [7]:
df.tail(5) # Display the last 5 rows of the dataset

          Date Category  Value   Product  Sales Region
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [10]:
### Accessing Data From Dataframe
df

          Date Category  Value   Product  Sales Region
0   2023-01-01        A   28.0  Product1  754.0   East
1   2023-01-02        B   39.0  Product3  110.0  North
2   2023-01-03        C   32.0  Product2  398.0   East
3   2023-01-04        B    8.0  Product1  522.0   East
4   2023-01-05        B   26.0  Product3  869.0  North
5   2023-01-06        B   54.0  Product3  192.0   West
6   2023-01-07        A   16.0  Product1  936.0   East
7   2023-01-08        C   89.0  Product1  488.0   West
8   2023-01-09        C   37.0  Product3  772.0   West
9   2023-01-10        A   22.0  Product2  834.0   West
10  2023-01-11        B    7.0  Product1  842.0  North
11  2023-01-12        B   60.0  Product2    NaN   West
12  2023-01-13        A   70.0  Product3  628.0  South
13  2023-01-14        A   69.0  Product1  423.0   East
14  2023-01-15        A   47.0  Product2  893.0   West
15  2023-01-16        C    NaN  Product1  895.0  North
16  2023-01-17        C   93.0  Product2  511.0  South
17  2023-01-18        C    NaN  Product1  108.0   West
18  2023-01-19        A   31.0  Product2  578.0   West
19  2023-01-20        A   59.0  Product1  736.0   East
20  2023-01-21        C   82.0  Product3  606.0  South
21  2023-01-22        C   37.0  Product2  992.0  South
22  2023-01-23        B   62.0  Product3  942.0  North
23  2023-01-24        C   92.0  Product2  342.0   West
24  2023-01-25        A   24.0  Product2  458.0   East
25  2023-01-26        C   95.0  Product1  584.0   West
26  2023-01-27        C   71.0  Product2  619.0  North
27  2023-01-28        C   56.0  Product2  224.0  North
28  2023-01-29        B    NaN  Product3  617.0  North
29  2023-01-30        C   51.0  Product2  737.0  South
30  2023-01-31        B   50.0  Product3  735.0   West
31  2023-02-01        A   17.0  Product2  189.0   West
32  2023-02-02        B   63.0  Product3  338.0  South
33  2023-02-03        C   27.0  Product3    NaN   East
34  2023-02-04        C   70.0  Product3  669.0   West
35  2023-02-05        B   60.0  Product2    NaN   West
36  2023-02-06        C   36.0  Product3  177.0   East
37  2023-02-07        C    2.0  Product1    NaN  North
38  2023-02-08        C   94.0  Product1  408.0  South
39  2023-02-09        A   62.0  Product1  155.0   West
40  2023-02-10        B   15.0  Product1  578.0   East
41  2023-02-11        C   97.0  Product1  256.0   East
42  2023-02-12        A   93.0  Product3  164.0   West
43  2023-02-13        A   43.0  Product3  949.0   East
44  2023-02-14        A   96.0  Product3  830.0   East
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [24]:
import pandas as pd

# Create a DataFrame with custom alphabetic index labels
data = {
    'Name': ['Krish', 'John', 'Ram'],
    'Age': [25, 30, 28],
    'City': ['Bangalore', 'New York', 'Delhi']
}

df = pd.DataFrame(data, index=['a', 'b', 'c'])  # Set alphabetic labels as index
print(df)

    Name  Age       City
a  Krish   25  Bangalore
b   John   30   New York
c    Ram   28      Delhi

In [27]:
# loc → label-based indexing (selects data using the index label)

print(df.loc['a'] ,"\n")        # Select the row whose index label is 'a'
print(df.loc['b'],"\n")        # Select the row whose index label is 'b'
print(df.loc['a':'b'],"\n")    # Select rows from label 'a' to 'b' (both included)
print(df.loc['a','Name']) # Select value at row label 'a' and column 'Name'

Name        Krish
Age            25
City    Bangalore
Name: a, dtype: object

Name        John
Age           30
City    New York
Name: b, dtype: object

    Name  Age       City
a  Krish   25  Bangalore
b   John   30   New York

Krish

In [28]:

# iloc → integer location indexing (selects data using row/column position)

print(df.iloc[0],"\n")         # Select the first row using position 0
print(df.iloc[1],"\n")         # Select the second row using position 1
print(df.iloc[0:2],"\n")       # Select rows from position 0 to 1 (2 is excluded)
print(df.iloc[0,1])       # Select value at first row and second column

Name        Krish
Age            25
City    Bangalore
Name: a, dtype: object

Name        John
Age           30
City    New York
Name: b, dtype: object

    Name  Age       City
a  Krish   25  Bangalore
b   John   30   New York

25

In [32]:
data={
    'Name':['Krish','John','Jack'],
    'Age':[25,30,45],
    'City':['Bangalore','New York','Florida'],
    'Domain':['DataAnalyst' ,'DataScientist' , 'ML Engineer']
}
df=pd.DataFrame(data)
print(df)
print(type(df))

    Name  Age       City         Domain
0  Krish   25  Bangalore    DataAnalyst
1   John   30   New York  DataScientist
2   Jack   45    Florida    ML Engineer
<class 'pandas.core.frame.DataFrame'>

In [ ]:
df['Name']  # Select the 'Name' column from the DataFrame

0    Krish
1     John
2     Jack
Name: Name, dtype: object

In [30]:
df.loc[0]  # Select the row with index label 0 from the DataFrame

Name            Krish
Age                25
City        Bangalore
Domain    DataAnalyst
Name: 0, dtype: object

In [31]:
df.iloc[0] # Select the first row of the DataFrame using integer position

Name            Krish
Age                25
City        Bangalore
Domain    DataAnalyst
Name: 0, dtype: object

In [34]:
df

    Name  Age       City
0  Krish   25  Bangalore
1   John   30   New York
2   Jack   45    Florida

In [ ]:
## Accessing a specified element
df.at[2,'Age'] ## Get the value at row label 2 and column 'Age' using label-based access.

45

In [ ]:
df.at[2,'Name'] # Get the value at row label 2 and column 'Name' using label-based access.

'Jack'

In [ ]:
## Accessing a specified element using iat
df.iat[2,2] #  # Get the value at row position 2 and column position 2 using integer position.

'Florida'

In [33]:
df

    Name  Age       City         Domain
0  Krish   25  Bangalore    DataAnalyst
1   John   30   New York  DataScientist
2   Jack   45    Florida    ML Engineer

In [35]:
### Data Manipulation with Dataframe
df

    Name  Age       City         Domain
0  Krish   25  Bangalore    DataAnalyst
1   John   30   New York  DataScientist
2   Jack   45    Florida    ML Engineer

In [36]:
## Adding a column
df['Salary']=[50000,60000,70000]
df

    Name  Age       City         Domain  Salary
0  Krish   25  Bangalore    DataAnalyst   50000
1   John   30   New York  DataScientist   60000
2   Jack   45    Florida    ML Engineer   70000

In [ ]:
## Remove a column
df.drop('Salary',axis=1,inplace=True)
# axis=0 → drop row , axis is the parameter of drop() function
# axis=1 → drop column
# inplace=True → permanently removes the row or column from the original DataFrame . It modify the original DataFrame
# inplace is a parameter of drop() function that modifies the original DataFrame directly and True is a value(argument) of this parameter

In [47]:
df

    Name  Age       City
0  Krish   25  Bangalore
1   John   30   New York
2   Jack   45    Florida

In [ ]:
## Add age to the column
df['Age']=df['Age']+1  # Increase all values in the 'Age' column by 1
df

    Name  Age       City
0  Krish   26  Bangalore
1   John   31   New York
2   Jack   46    Florida

In [37]:
df.drop(0,inplace=True) # Remove the row with index label 0 from the DataFrame

In [38]:
df

   Name  Age      City         Domain  Salary
1  John   30  New York  DataScientist   60000
2  Jack   45   Florida    ML Engineer   70000

In [53]:
df=pd.read_csv('sales_data.csv')
df.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [54]:
# Display the data types of each column
print("Data types:\n", df.dtypes)

# Describe the DataFrame
print("Statistical summary:\n", df.describe())

Data types:
 Transaction ID        int64
Date                 object
Product Category     object
Product Name         object
Units Sold            int64
Unit Price          float64
Total Revenue       float64
Region               object
Payment Method       object
dtype: object
Statistical summary:
        Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000

In [ ]:
df.describe() # describe() → shows statistical summary (count, mean, std, min, max, etc.)

       Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000